# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://tramdoman.github.io/'
baseurl:             'app-dev-2/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Tram Doman
  url:               https://tramdoman.com
  email:             tramdoman@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
